name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    
    # 设置编译环境
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease  && cd ./app && tree
      
    # 获取apk版本号
    - name: Read value from Properties-file
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './version.properties'
        property: 'versionName'
    
    # 上传资源到Artifact
    - name: Upload Apk To Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ steps.read_property.outputs.value }}
        path: app/build/outputs/apk/release/idioms_v${{ steps.read_property.outputs.value }}_release.apk
        if-no-files-found: error
   
   # 从Artifact下载资源
    - name: Download Apk From Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ steps.read_property.outputs.value }}
   
    
    - name: diff
      run: |
          sudo apt-get install bsdiff -y
          wget https://github.com/LiteraturePro/test/releases/download/1.0.1/idioms_v1.0.1_release.apk
          bsdiff idioms_v1.0.1_release.apk idioms_v1.0.2_release.apk idioms_v1.0.2.patch
          
    # 上传资源到Artifact
    - name: Upload Apk To Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: idioms_v1.0.2.patch
        path: idioms_v1.0.2.patch
        if-no-files-found: error
      
