name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    
    # 设置编译环境
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease 
      
    # 获取apk版本号
    - name: Read value from Properties-file
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: './version.properties'
        property: 'versionName'
    
    # 上传资源到Artifact
    - name: Upload Apk To Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ steps.read_property.outputs.value }}
        path: app/build/outputs/apk/release/idioms_v${{ steps.read_property.outputs.value }}_release.apk
        if-no-files-found: error
   
   # 从Artifact下载资源
    - name: Download Apk From Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ steps.read_property.outputs.value }}
   
    
    - name: Bsdiff The  Apk
      run: |
          wget https://idiom-file.wxiou.cn/vnTevc8KFFKhLzKlUxyuQVTvLawgpTaQl89WB5BQ.apk
          find ./ -name '*.apk' -exec basename {} > apk.txt \;
          wget https://lc-gluttony.s3.amazonaws.com/9WTW1sBG7ANz/8hWoLYkcVz2ekQ00pIhP6tpv5BaU6XXg/d.sh
          bash d.sh
          
    # 上传资源到Artifact
    - name: Upload Apk To Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: idioms_v${{ steps.read_property.outputs.value }}_release.patch
        path: ./idioms_v${{ steps.read_property.outputs.value }}_release.patch
        if-no-files-found: error
      
